Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,122 +1,193 @@
 version: 2.1
 
 executors:
-  docker-executor:
+  java-node-docker-executor:
     docker:
-      - image: circleci/node:16  # Adjust Node.js version as needed
+      - image: circleci/openjdk:11-jdk
+    environment:
+      JAVA_HOME: /usr/local/openjdk-11
+      GROOVY_HOME: /usr/local/groovy
+      PATH: /usr/local/groovy/bin:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+    working_directory: /home/circleci/project
 
 jobs:
-  setup:
-    executor: docker-executor
-    parameters:
-      GIT_SOURCE_CODE_URL:
-        type: string
-        default: "https://github.com/bharathkoptit/build_js_react_app.git"
-      SOURCE_CODE_BRANCH_NAME:
-        type: string
-        default: "master"
+  install_dependencies:
+    executor: java-node-docker-executor
     steps:
       - checkout
       - run:
-          name: Print Parameters
+          name: Install Node.js and npm
           command: |
-            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
-            echo "SOURCE_CODE_BRANCH_NAME: << parameters.SOURCE_CODE_BRANCH_NAME >>"
+            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
+            sudo apt-get install -y nodejs
+            node --version
+            npm --version
       - run:
-          name: Prepare Directory
+          name: Install Groovy
           command: |
-            if [ -d ~/project ]; then
-              rm -rf ~/project
-            fi
-            mkdir -p ~/project
-      - run:
-          name: Checkout Repository
-          command: |
-            git clone << parameters.GIT_SOURCE_CODE_URL >> ~/project
-            cd ~/project
-            if git show-ref --verify --quiet refs/heads/<< parameters.SOURCE_CODE_BRANCH_NAME >>; then
-              git checkout << parameters.SOURCE_CODE_BRANCH_NAME >>
-            else
-              echo "Branch '<< parameters.SOURCE_CODE_BRANCH_NAME >>' not found. Available branches:"
-              git branch -r
-              exit 1
-            fi
-      - run:
-          name: Install Node.js Dependencies
-          command: |
-            cd ~/project
-            npm install
-      - run:
-          name: Install SDKMAN and Groovy
-          command: |
-            curl -s "https://get.sdkman.io" | bash
-            source "$HOME/.sdkman/bin/sdkman-init.sh"
-            sdk install groovy 3.0.9
-            # Set up environment variables for Groovy
-            echo 'export GROOVY_HOME="$HOME/.sdkman/candidates/groovy/current"' >> $BASH_ENV
-            echo 'export PATH="$GROOVY_HOME/bin:$PATH"' >> $BASH_ENV
-      - run:
-          name: Load Environment Variables
-          command: |
-            source $BASH_ENV
+            wget https://archive.apache.org/dist/groovy/4.0.11/distribution/apache-groovy-sdk-4.0.11.zip
+            unzip apache-groovy-sdk-4.0.11.zip
+            sudo mv groovy-4.0.11 /usr/local/groovy
+            export PATH=$PATH:/usr/local/groovy/bin
             groovy --version
       - run:
-          name: Load and Execute Groovy Scripts
+          name: Install SonarQube Scanner
           command: |
-            cd ~/project
-            baseDir="${PWD}/Jenkins/shared-libraries"
-            loadAndExecuteGroovyScript() {
+            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
+            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
+            sudo mv sonar-scanner-4.6.2.2472-linux /usr/local/sonar-scanner
+            export PATH=$PATH:/usr/local/sonar-scanner/bin
+            sonar-scanner --version
+      - run:
+          name: Install Docker
+          command: |
+            curl -fsSL https://get.docker.com -o get-docker.sh
+            sh get-docker.sh
+            sudo usermod -aG docker $USER
+            docker --version
+
+  load_scripts:
+    executor: java-node-docker-executor
+    steps:
+      - checkout
+      - run:
+          name: Load Scripts
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            export PATH=$PATH:/usr/local/groovy/bin
+
+            # Debugging: Show current working directory
+            echo "Current working directory: $(pwd)"
+
+            # Debugging: List contents of current working directory
+            echo "Contents of current working directory:"
+            ls -R
+
+            # Directly use the baseDir provided
+            baseDir="${CIRCLE_WORKING_DIRECTORY}/Jenkins/shared-libraries"
+            echo "Base directory: ${baseDir}"
+            
+            # Debugging: List contents of base directory
+            echo "Contents of base directory:"
+            ls -R "${baseDir}" || echo "Base directory does not exist"
+
+            loadScript() {
               type=$1
               technology=$2
               scriptName=$3
               scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
-              if [ -f ${scriptPath} ]; then
-                echo "Executing ${scriptPath}"
-                groovy ${scriptPath}
+              echo "Loading script: ${scriptPath}"  # Debugging line
+              if [ -f "${scriptPath}" ]; then
+                cat "${scriptPath}"
               else
-                echo "Script ${scriptPath} not found!"
+                echo "Script not found: ${scriptPath}"
                 exit 1
               fi
             }
-            loadAndExecuteGroovyScript "vars/common/scm-util" "git" "GitCheckout"
-            loadAndExecuteGroovyScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs"
-            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerUtil"
-            loadAndExecuteGroovyScript "vars/common" "containerPublish" "DockerHubPublish"
-            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerScan"
-            loadAndExecuteGroovyScript "src/org/common" "build" "BuildWithNpm"
-            loadAndExecuteGroovyScript "src/org/common" "unitTest" "UnitTestWithNpm"
+
+            gitCheckoutScript=$(loadScript "vars/common/scm-util" "git" "GitCheckout")
+            sonarScript=$(loadScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs")
+            dockerBuildScript=$(loadScript "vars/common" "dockerUtil" "DockerUtil")
+            dockerPublishScript=$(loadScript "vars/common" "containerPublish" "DockerHubPublish")
+            dockerScanScript=$(loadScript "vars/common" "dockerUtil" "DockerScan")
+            buildWithNpmScript=$(loadScript "src/org/common" "build" "BuildWithNpm")
+            unitTestWithNpmScript=$(loadScript "src/org/common" "unitTest" "UnitTestWithNpm")
+
+            echo "${gitCheckoutScript}" > gitCheckoutScript.groovy
+            echo "${sonarScript}" > sonarScript.groovy
+            echo "${dockerBuildScript}" > dockerBuildScript.groovy
+            echo "${dockerPublishScript}" > dockerPublishScript.groovy
+            echo "${dockerScanScript}" > dockerScanScript.groovy
+            echo "${buildWithNpmScript}" > buildWithNpmScript.groovy
+            echo "${unitTestWithNpmScript}" > unitTestWithNpmScript.groovy
 
   build:
-    docker:
-      - image: circleci/node:16  # Adjust Node.js version as needed
-    parameters:
-      DOCKER_REPO:
-        type: string
-        default: "bharathoptdocker"
-      DOCKER_IMAGE_NAME:
-        type: string
-        default: "optit-lab-service"
-      DOCKER_IMAGE_TAG:
-        type: string
-        default: "latest"
+    executor: java-node-docker-executor
     steps:
-      - checkout
       - run:
-          name: Build Docker Image
+          name: Build
           command: |
-            cd ~/project
-            docker build -t << parameters.DOCKER_REPO >>/<< parameters.DOCKER_IMAGE_NAME >>:<< parameters.DOCKER_IMAGE_TAG >> .
+            export JAVA_HOME=/usr/local/openjdk-11
+            npm run build
+
+  test:
+    executor: java-node-docker-executor
+    steps:
+      - run:
+          name: Unit Test
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            npm test
+
+  sonar_analysis:
+    executor: java-node-docker-executor
+    steps:
+      - run:
+          name: SonarQube Analysis
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            groovy -e "${sonarScript}.performSonarCloudAnalysis('${SONAR_PROJECT_KEY}', '${SONAR_ORGANIZATION}', '${SONAR_SOURCES_DIR}', '${SONAR_TOKEN}')"
+
+  docker_build:
+    docker:
+      - image: circleci/openjdk:11-jdk
+    steps:
+      - setup_remote_docker:
+          version: 20.10.7
+      - run:
+          name: Docker Build
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            groovy -e "${dockerBuildScript}.dockerBuild('${DOCKER_IMAGE_NAME}', '${DOCKER_IMAGE_TAG}')"
+
+  docker_scan:
+    docker:
+      - image: circleci/openjdk:11-jdk
+    steps:
+      - setup_remote_docker:
+          version: 20.10.7
+      - run:
+          name: Docker Scan
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            groovy -e "${dockerScanScript}.dockerScan('${DOCKER_IMAGE_NAME}')"
+
+  docker_publish:
+    docker:
+      - image: circleci/openjdk:11-jdk
+    steps:
+      - setup_remote_docker:
+          version: 20.10.7
+      - run:
+          name: Docker Publish
+          command: |
+            export JAVA_HOME=/usr/local/openjdk-11
+            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+            groovy -e "${dockerPublishScript}.publishToContainer('${DOCKER_IMAGE_NAME}', '${DOCKER_REPO}', '${DOCKER_IMAGE_TAG}', '${DOCKER_CREDENTIAL}')"
 
 workflows:
   version: 2
-  setup_and_build:
+  build_and_deploy:
     jobs:
-      - setup:
-          GIT_SOURCE_CODE_URL: "https://github.com/bharathkoptit/build_js_react_app.git"
-          SOURCE_CODE_BRANCH_NAME: "master"
+      - install_dependencies
+      - load_scripts:
+          requires:
+            - install_dependencies
       - build:
           requires:
-            - setup
-          DOCKER_REPO: "bharathoptdocker"
-          DOCKER_IMAGE_NAME: "optit-lab-service"
-          DOCKER_IMAGE_TAG: "latest"
+            - load_scripts
+      - test:
+          requires:
+            - build
+      - sonar_analysis:
+          requires:
+            - test
+      - docker_build:
+          requires:
+            - sonar_analysis
+      - docker_scan:
+          requires:
+            - docker_build
+      - docker_publish:
+          requires:
+            - docker_scan
