Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,8 +58,8 @@ jobs:
           name: Install SonarScanner
           command: |
             curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
-            if [ $? -ne 0 ]; then
-              echo "Failed to download SonarScanner"
+            if [ $? -ne 0 ] || [ ! -f /tmp/sonar-scanner.zip ]; then
+              echo "Failed to download SonarScanner or the file does not exist"
               exit 1
             fi
             
@@ -70,6 +70,7 @@ jobs:
             fi
             sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.9.2.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
             sudo chmod +x /usr/local/bin/sonar-scanner
+
 
 
       - run:
