Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -55,22 +55,29 @@ jobs:
             groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy
 
       - run:
+          name: Download and Verify SonarScanner
+          command: |
+            for i in 1 2 3; do
+              curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
+              if [ $? -eq 0 ]; then
+                break
+              fi
+              echo "Download attempt $i failed, retrying..."
+              sleep 5
+            done
+
+            echo "Verifying SonarScanner ZIP file..."
+            unzip -t /tmp/sonar-scanner.zip || {
+              echo "SonarScanner ZIP file verification failed."
+              exit 1
+            }
+
+      - run:
           name: Install SonarScanner
           command: |
-            curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
-            if [ $? -ne 0 ]; then
-              echo "Failed to download SonarScanner"
-              exit 1
-            fi
-            
             sudo unzip /tmp/sonar-scanner.zip -d /opt/sonar-scanner
-            if [ $? -ne 0 ]; then
-              echo "Failed to unzip SonarScanner"
-              exit 1
-            fi
             sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.9.2.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
             sudo chmod +x /usr/local/bin/sonar-scanner
-
 
       - run:
           name: Verify SonarScanner Installation
