Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,28 +75,23 @@ jobs:
             fi
 
       - run:
-          name: Install Groovy
+          name: Check Groovy Installation
           command: |
-            sudo apt-get update
-            sudo apt-get install -y openjdk-11-jdk  # Required for Groovy
-            wget https://archive.apache.org/dist/groovy/your_version/groovy-your_version-bin.zip
-            unzip groovy-your_version-bin.zip
-            sudo mv groovy-your_version /opt/groovy
-            sudo ln -s /opt/groovy/bin/groovy /usr/bin/groovy
-            groovy -version  # Verify installation
-
-  build:
-    executor: node-executor
-    steps:
-      - checkout:
-          path: ~/project
+            if ! command -v groovy &> /dev/null; then
+              sudo apt-get update
+              sudo apt-get install -y groovy
+            else
+              echo "Groovy is already installed"
+            fi
 
       - run:
-          name: Load and Execute Build Script
+          name: Load and Execute Groovy Scripts
           command: |
             cd ~/project
+            # Define baseDir for the project
             baseDir="${PWD}/Jenkins/shared-libraries"
             
+            # Function to load and execute a Groovy script
             loadAndExecuteGroovyScript() {
               type=$1
               technology=$2
@@ -111,16 +106,56 @@ jobs:
               fi
             }
             
+            # Load and execute required scripts
+            loadAndExecuteGroovyScript "vars/common/scm-util" "git" "GitCheckout"
+            loadAndExecuteGroovyScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs"
+            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerUtil"
+            loadAndExecuteGroovyScript "vars/common" "containerPublish" "DockerHubPublish"
+            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerScan"
             loadAndExecuteGroovyScript "src/org/common" "build" "BuildWithNpm"
+            loadAndExecuteGroovyScript "src/org/common" "unitTest" "UnitTestWithNpm"
 
-  # Add additional jobs here (e.g., unit_test, sonar_analysis) as needed
+  build:
+    executor: node-executor
+    steps:
+      - checkout:
+          path: ~/project
+
+      - run:
+          name: Print Parameters
+          command: |
+            echo "GIT_SOURCE_CODE_URL: << parameters.GIT_SOURCE_CODE_URL >>"
+            echo "SOURCE_CODE_BRANCH_NAME: << parameters.SOURCE_CODE_BRANCH_NAME >>"
+
+      - run:
+          name: Load and Execute Build Groovy Script
+          command: |
+            cd ~/project
+            baseDir="${PWD}/Jenkins/shared-libraries"
+
+            loadAndExecuteGroovyScript() {
+              type=$1
+              technology=$2
+              scriptName=$3
+              scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
+              if [ -f ${scriptPath} ]; then
+                echo "Executing ${scriptPath}"
+                groovy ${scriptPath}
+              else
+                echo "Script ${scriptPath} not found!"
+                exit 1
+              fi
+            }
+
+            loadAndExecuteGroovyScript "src/org/common" "build" "BuildWithNpm"
 
 workflows:
   version: 2
-  setup_and_load:
+  setup_and_build:
     jobs:
-      - setup
+      - setup:
+          GIT_SOURCE_CODE_URL: "https://github.com/bharathkoptit/build_js_react_app.git"
+          SOURCE_CODE_BRANCH_NAME: "master"
       - build:
           requires:
             - setup
-      # Add additional job dependencies here
