Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,23 +6,39 @@ executors:
       - image: circleci/python:3.8
 
 jobs:
-  build:
+  setup:
     executor: default
     steps:
       - checkout
 
       # Install required packages
       - run:
-          name: Install Java and Groovy
+          name: Install Java and other packages
           command: |
             sudo apt-get update
             sudo apt-get install -y unzip wget openjdk-11-jdk
+
+      # Set JAVA_HOME environment variable
+      - run:
+          name: Set JAVA_HOME
+          command: |
+            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
+            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
+            source $BASH_ENV
+
+      # Install Groovy
+      - run:
+          name: Install Groovy
+          command: |
             wget https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-5.0.0-alpha-9.zip -O groovy.zip
             sudo unzip groovy.zip -d /opt
             sudo ln -sf /opt/groovy-5.0.0-alpha-9/bin/groovy /usr/local/bin/groovy
             sudo chmod +x /opt/groovy-5.0.0-alpha-9/bin/groovy
-            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
-            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
+
+      # Set GROOVY_HOME and update PATH environment variable
+      - run:
+          name: Set GROOVY_HOME
+          command: |
             echo 'export GROOVY_HOME=/opt/groovy-5.0.0-alpha-9' >> $BASH_ENV
             echo 'export PATH=$GROOVY_HOME/bin:$PATH' >> $BASH_ENV
             source $BASH_ENV
@@ -49,28 +65,46 @@ jobs:
             npm install
             npm run build
 
-      # Run Groovy scripts
-      - run:
-          name: Run Groovy Scripts
-          command: |
-            # Ensure Groovy scripts are executable and run them
-            chmod +x path/to/your/script.groovy
-            groovy path/to/your/script.groovy
-
       # Optionally, run tests or other commands
       - run:
           name: Run tests
           command: |
             npm test
 
-      # Optionally, deploy or archive artifacts
-      # - run:
-      #     name: Deploy
-      #     command: |
-      #       # Your deployment commands here
+      # Load and execute Groovy scripts
+      - run:
+          name: Load and Execute Groovy Scripts
+          command: |
+            cd ~/project
+            # Define baseDir for the project
+            baseDir="${PWD}/Jenkins/shared-libraries"
+            
+            # Function to load and execute a Groovy script
+            loadAndExecuteGroovyScript() {
+              type=$1
+              technology=$2
+              scriptName=$3
+              scriptPath="${baseDir}/${type}/${technology}/${scriptName}.groovy"
+              if [ -f ${scriptPath} ]; then
+                echo "Executing ${scriptPath}"
+                groovy ${scriptPath}
+              else
+                echo "Script ${scriptPath} not found!"
+                exit 1
+              fi
+            }
+            
+            # Load and execute required scripts
+            loadAndExecuteGroovyScript "vars/common/scm-util" "git" "GitCheckout"
+            loadAndExecuteGroovyScript "vars/common" "codeAnalysis" "PerformSonarAnalysisForReactjs"
+            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerUtil"
+            loadAndExecuteGroovyScript "vars/common" "containerPublish" "DockerHubPublish"
+            loadAndExecuteGroovyScript "vars/common" "dockerUtil" "DockerScan"
+            loadAndExecuteGroovyScript "src/org/common" "build" "BuildWithNpm"
+            loadAndExecuteGroovyScript "src/org/common" "unitTest" "UnitTestWithNpm"
 
 workflows:
   version: 2
   build:
     jobs:
-      - build
+      - setup
