Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -55,12 +55,22 @@ jobs:
             groovy Jenkins/shared-libraries/src/org/common/unitTest/UnitTestWithNpm.groovy
 
       - run:
-          name: Install SonarScanner
-          command: |
-            curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
-            sudo unzip /tmp/sonar-scanner.zip -d /opt/sonar-scanner
-            sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.9.2.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
-            sudo chmod +x /usr/local/bin/sonar-scanner
+          - run:
+              name: Install SonarScanner
+              command: |
+                curl -L -o /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.2747-linux.zip
+                if [ $? -ne 0 ]; then
+                  echo "Failed to download SonarScanner"
+                  exit 1
+                fi
+                sudo unzip /tmp/sonar-scanner.zip -d /opt/sonar-scanner
+                if [ $? -ne 0 ]; then
+                  echo "Failed to unzip SonarScanner"
+                  exit 1
+                fi
+                sudo ln -sf /opt/sonar-scanner/sonar-scanner-4.9.2.2747-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
+                sudo chmod +x /usr/local/bin/sonar-scanner
+
 
 
       - run:
